name: Testing

# Add a concurrency group incase a tag is created, deleted, and then recreated while a release is in progress.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Only run this workflow when a tag is pushed when the tag starts with "v".
on:
  release:
    types: [created]

# So we can use the GitHub API to create releases with the run token.
permissions:
  contents: write

jobs:
  Testing:
    if: github.event.release.prerelease == true #only run on pre-release tags.
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Ktisis/
        shell: bash
    env:
      DALAMUD_HOME: /tmp/dalamud
      IsCI: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true # Grab any submodules that may be required

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Download Dalamud Library
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/latest.zip -O /tmp/dalamud.zip
          unzip /tmp/dalamud.zip -d /tmp/dalamud

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build plugin in release mode
        run: dotnet build -c Release --no-restore --nologo -o ./bin/Release

      - name: Generate Checksums
        working-directory: Ktisis/bin/Release/Ktisis
        run: |
          sha512sum latest.zip >> checksums.sha512

      - name: Update Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          allowUpdates: true
          artifacts: "./Ktisis/bin/Release/Ktisis/latest.zip,./Ktisis/bin/Release/Ktisis/checksums.sha512"
          bodyFile: '.github/release-notices.md'
          generateReleaseNotes: true
          updateOnlyUnreleased: false

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release Artifacts
          path: |
            Ktisis/bin/Release/Ktisis/latest.zip
            Ktisis/bin/Release/Ktisis/checksums.sha512

      - name: Update repo.json
        working-directory: .
        run: |
          git config --local user.name "github-actions [bot]"
          git config --local user.email "github-actions@users.noreply.github.com"
          git fetch origin main && git checkout main

          release_version=$(echo ${{ github.ref_name }} | sed 's/^v//')
          repo_url=$(echo ${{ github.server_url }}/${{ github.repository }} | sed 's/#/\\#/g')

          sed -i repo.json -E \
              -e 's#"TestingAssemblyVersion": "([0-9]*\.){2,3}[0-9]*"#"TestingAssemblyVersion": "'"$release_version"'"#' \
              -e 's#"DownloadLinkTesting": "[^"]*"#"DownloadLinkTesting": "'"$repo_url/releases/download/${{ github.ref_name }}/latest.zip"'"#g' \
              -e 's#"DownloadLinkUpdate": "[^"]*"#"DownloadLinkUpdate": "'"$repo_url/releases/download/${{ github.ref_name }}/latest.zip"'"#g'

          git add repo.json
          git commit -m "Update repo.json for ${{ github.ref_name }}"
          
          git push origin HEAD:main
